AllCops:
  Exclude:
    - wor-paginate.gemspec
    - spec/spy.rb
    - spec/dummy/db/**/*
    - spec/dummy/config/**/*
    - spec/spec_helper.rb


Documentation:
  Enabled: false

LineLength:
  Max: 99

FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
