language: ruby
rvm:
  - 2.3.8
  - 2.4.7
  - 2.5.6
  - 2.6.4
  - ruby-head

before_install:
  - gem install bundler -v 2.0.1

install:
  - bundle _2.0.1_ install --retry=3
  - bundle exec rake db:migrate RAILS_ENV=test -f spec/dummy/Rakefile

script:
  - bundle exec rubocop lib spec --format simple
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter

matrix:
  allow_failures:
    - rvm : ruby-head
