language: ruby
rvm:
  - 2.3.3
  - 2.4.0
  - 2.4.2
  - 2.5.0
  - ruby-head

install:
  - gem install bundler -v 1.16.4
  - bundle _1.16.4_ install --retry=3
  - bundle exec rake db:migrate RAILS_ENV=test -f spec/dummy/Rakefile

script:
  - bundle exec rubocop lib spec --format simple
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
