language: ruby
rvm:
  - 2.2.2
  - 2.3.3
  - 2.4.0

install:
  - gem install bundler
  - bundle install --retry=3
  - bundle exec rake db:migrate RAILS_ENV=test -f spec/dummy/Rakefile

before_script:
  - gem install danger --version '~> 5.0'
  - bundle exec danger

script:
  - bundle exec rubocop --format simple
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
